Sbaud/iac diff scan
GitGuardian/py-gitguardian pull request #66
Opened 2023-07-03 13:39 UTC by sylvain-baud-gg

Add iac diff scan to pyGitGuardian.

We use the same implementation logic than iac directory scan.

Careful, just like iac directory scan, iac diff scan needs to access the data argument of request. Therefore iac_diff_scan by pass the GGClient.post method and directly call GGClient.request.

2023-07-03 13:47 UTC, gg-teolohrer commented on changelog.d/20230703_154225_sylvain.baud.ext_iac_diff_scan.md
> +- iac_diff_scan added to GGClient. This allow to scan two directories and categorised found invidents as new, unchanged or deleted.
```suggestion
- `iac_diff_scan` added to GGClient. This allows scanning two directories for IaC vulnerabilities and categorise incidents as new, unchanged or deleted.
```

2023-07-03 16:22 UTC, GG-HH approved these changes

2023-07-04 09:04 UTC, agateau-gg requested changes
Minor remark on doc.

2023-07-04 09:52 UTC, sylvain-baud-gg commented on pygitguardian/client.py
> +    # For IaC diff Scans
Added docstring to `iac_directory_scan` and `iac_diff_scan`

2023-07-04 13:23 UTC, agateau-gg approved these changes
Nice! Thanks for adding a docstring to `iac_directory_scan()` too! :+1:

2023-07-04 13:51 UTC, merged