WIP: Add support for Secret Incidents API endpoints
GitGuardian/py-gitguardian pull request #84
Opened 2023-12-29 16:05 UTC by irgeek

The PR adds models and methods to handle the [Secret Incidents ](https://api.gitguardian.com/docs#tag/Secret-Incidents)API endpoints. It still needs a changelog entry and (probably) some cleanup, but I wanted to get some feedback before I put too much work into it. As requested I've sliced the changes up in to several commits for ease of review.

2023-12-29 16:29 UTC, irgeek commented
The `lint` check is failing because `ggshield` complains about the API key.

2024-01-04 17:31 UTC, agateau-gg requested changes
Wow, that's some huge work, thanks!

I made some remarks inline, but here are some more general ones:

I'd rather avoid too deep file hierarchies and make the following changes:
- merge all incident_models code into an incident_models.py module, similar to what you did with source_models.py.
- merge utils/tools.py into utils/__init__.py

I think an utils package should not contain model-specific code so I would move `load_incident_response()` to incident_models.py.

I am not fond of the `_url` param added to `GGClient.request()`. I understand this is required to support paging, but I'd rather not add such a parameter to py-gitguardian public API. Maybe you can take the bulk of the `requests()` method minus the endpoint-to-url code, move it to utils and have both `GGClient.request()` and code using paging to use it?

Some of the functions you added take *a lot* of optional arguments. You should make them keyword-only arguments.

2024-01-04 17:31 UTC, agateau-gg commented on Pipfile
> +strenum = "*"
Adding StrEnum here is not required: non-dev dependencies only need to be in `setup.py`.

2024-01-04 17:31 UTC, agateau-gg commented on setup.py
> +        "strenum",
Can you pin StrEnum to `>=0.4, <0.5` (even if you are very close to StrEnum maintainer 😉)?

2024-01-04 17:31 UTC, agateau-gg commented on pygitguardian/incident_models/constants.py
> +    removed = auto()
Can you make these values upper-case, like the others?

2024-01-04 17:31 UTC, agateau-gg commented on pygitguardian/incident_models/__init__.py
> +        return self.id
I'd rather not have such magic behavior, using `.id` is simple enough.

2024-01-04 17:31 UTC, agateau-gg commented on pygitguardian/utils/tools.py
> +    """Count the number of None values in a sequence"""
```suggestion
    """Count the number of not-None values in a sequence"""
```

2024-01-04 17:31 UTC, agateau-gg commented on pygitguardian/utils/tools.py
> +    Ensure only one value in a sequence is None.
```suggestion
    Ensure only one value in a sequence is not None.
```

2024-01-04 17:31 UTC, agateau-gg commented on pygitguardian/utils/tools.py
> +    return sum(0 if v is None else 1 for v in seq)
nit: can be slightly simplified:
```suggestion
    return sum(1 for v in seq if v is not None)
```

2024-01-04 17:31 UTC, agateau-gg commented on pygitguardian/source_models.py
> +    visibility: str  # TODO: Really? str
Are those TODO actionable? If not, better remove them.

2024-01-04 17:31 UTC, agateau-gg commented on pygitguardian/incident_models/__init__.py
> +class Match(Base, FromDictMixin):
There is already a `Match` class in `models`, can we name this one `OccurrenceMatch`?

2024-08-28 07:27 UTC, agateau-gg commented
Sorry I have to close this PR. It has not moved for several months now. Meanwhile incident support has just been added by #114.

2024-08-28 07:27 UTC, closed without merging