feat(metadata): add general server payload maximum to secret scan preferences
GitGuardian/py-gitguardian pull request #85
Opened 2024-01-03 09:55 UTC by fnareoh

I hesitated on where to store the server payload in the GCC client but as I want to use it for secret scanning it seemed best there.

2024-01-03 15:02 UTC, agateau-gg requested changes

2024-01-03 15:02 UTC, agateau-gg commented on pygitguardian/client.py
> +            )
I think the maximum payload size should be a property of GGClient: all verticals could need it. I would turn this into:

```python
self.maximum_payload_size = metadata.preferences.get("general__maximum_payload_size", MAXIMUM_PAYLOAD_SIZE)
```

2024-01-03 15:02 UTC, agateau-gg commented on pygitguardian/config.py
> +GENERAL_MAXIMUM_PAYLOAD = 2621440  # 25MB
The `general__` part of the field name is an implementation detail of the server. I'd rather hide it and name this constant `MAXIMUM_PAYLOAD_SIZE`.

2024-01-09 15:54 UTC, agateau-gg requested changes
Looks good, just needs a changelog entry to document the new field. See https://github.com/GitGuardian/ggshield/blob/main/doc/dev/getting-started.md#changelog for details.

2024-01-10 08:58 UTC, fnareoh commented
Should be good now ? Sorry for missing scriv and thank you for the patient reviews :)

2024-01-11 09:09 UTC, agateau-gg commented
> GGShield fails in the lint job fails because the PR comes from a fork. I filed #87 to avoid that. The job should become green once this change is merged.

Ah, that did not go as expected: looks like GitHub takes the CI config from the branch being merged instead of the result of the merge. Force-merging it.

2024-01-11 09:09 UTC, merged